Numpy Basics


In [8]:
# import numpy as np 

# arr=np.array([1,2,3],[4,5,6])
# print(arr.ndim)

import numpy as np 

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.ndim)
# Output: 2

2


In [7]:
# print(arr.shape)
# print(aar.dtype)

In [9]:
arr=np.arange(1,10)
print(arr)


[1 2 3 4 5 6 7 8 9]


In [12]:
num=[]
for i in range(1,10):
 print(i)

1
2
3
4
5
6
7
8
9


In [13]:
#with step
with_step=np.arange(1,10,2)
print(with_step)


[1 3 5 7 9]


In [15]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr[1][1])

5


In [16]:
arr1=np.array([1,2,3,4,5,6,7,8,9])
arr[1:4]

array([[4, 5, 6]])

In [19]:
arr=np.array([1,2,3,4,5])
print(arr*2)
print(arr**2)
print(arr+2)

[ 2  4  6  8 10]
[ 1  4  9 16 25]
[3 4 5 6 7]


In [ ]:
#Used numpy terms
marks=np.array([56,49,90,34,50,45])

#average
print(np.average(marks))

#sum
print(np.sum(marks))

#min marks
print(np.min(marks))

#max marks
print(np.max(marks))

#median
print(np.median(marks))

#std
print(np.std(marks))


54.0
324
34
90
49.5
17.426034163476974


Temperature analysis


In [37]:
# temp=np.array([21,25,28,30,27,24,22])

# #average
# print("The average temperature is:",np.average(temp))

# #max 
# print("The maximum temperature is:",np.max(temp))

# #min
# print("The minimum temperature is:",np.min(temp))

# #temp above avg

# print("The temperature above average is:",[temp(temp> np.average(temp))])

# # temp[temp > avg_temp]

In [36]:
import numpy as np

temp = np.array([21, 25, 28, 30, 27, 24, 22])

# Average
avg_temp = np.average(temp)
print("The average temperature is:", avg_temp)

# Maximum
print("The maximum temperature is:", np.max(temp))

# Minimum
print("The minimum temperature is:", np.min(temp))

# Temperature above average
print("The temperature above average is:", temp[temp > avg_temp])

The average temperature is: 25.285714285714285
The maximum temperature is: 30
The minimum temperature is: 21
The temperature above average is: [28 30 27]


Sales Analysis
- Print the array dimensions.
- Print its shape.
- Find total sales.
- Find average sales.
- Find the highest sale.
- Find the lowest sale.
- Calculate total sales for each salesperson.
- Calculate total sales for each month.
- Find all sales greater than 1500.
- Increase every sales value by 10% and print the resulting array.

In [ ]:
sales = np.array([
    [1200, 1500, 1100],
    [1800, 1700, 1600],
    [900, 1200, 1400],
    [2000, 2100, 1900]
])

print(sales.ndim)
print(sales.shape)
#Total sales
print("The total sales is:",np.sum(sales))

#Average sales
print("The average sales is:",np.average(sales))

#Highest sale
print("The highest sale is:",np.max(sales))

#Lowest sale
print("The lowest sale is:",np.min(sales))

#Sales by each person
print("The sales of first salesperson is:",np.sum(sales[0]))

print("The sales of second salesperson is:",np.sum(sales[1]))

print("The sales of third salesperson is:",np.sum(sales[2]))

print("The sales of fourth salesperson is:",np.sum(sales[3]))

#sales by each month  for columns
print("The total sales of Baisakh is:",np.sum(sales,axis=0))

#sales by each salesperson: for rows 
print("The total sales of each salesperson is:",np.sum(sales,axis=1))

#sales greater than 1500
result=sales[sales>1500]
print("The sales greater than 1500 are:",result)

#Increase by 10 percent
new_sales=sales*1.1
print("Every sales increase by 10 percentage is:\n",new_sales)







2
(4, 3)
The total sales is: 18400
The average sales is: 1533.3333333333333
The highest sale is: 2100
The lowest sale is: 900
The sales of first salesperson is: 3800
The sales of second salesperson is: 5100
The sales of third salesperson is: 3500
The sales of fourth salesperson is: 6000
The total sales of Baisakh is: [5900 6500 6000]
The total sales of each salesperson is: [3800 5100 3500 6000]
The sales greater than 1500 are: [1800 1700 1600 2000 2100 1900]
Every sales increase by 10 percentage is:
 [[1320. 1650. 1210.]
 [1980. 1870. 1760.]
 [ 990. 1320. 1540.]
 [2200. 2310. 2090.]]
