In [3]:

import numpy as np

arr=np.array([10,25,30,45,50,65])
print(arr[(arr<30)] and [(arr>50)])


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [ ]:
marks= np.array([35,67,42,89,28])


result=np.where (marks>=40, "pass","fail")
print(result)


In [ ]:
salary=np.array([25000,35000,55000,30000])

new_salary=np.where(salary<=4000, salary*1.2, salary*1.1)
print(new_salary)


In [ ]:
print(np.sort(arr))

print(np.sort(arr)[::-1])

#argsort  return index instead of value
np.argsort(arr)

In [5]:
#unique values
import numpy as np
cities=['ktm','pokhara','chitwan','ktm']

new_cities=list(set(cities))
print(new_cities)
values,count= np.unique(cities, return_counts=True)
print(values)
print(count)

['ktm', 'chitwan', 'pokhara']
['chitwan' 'ktm' 'pokhara']
[1 2 1]


In [10]:
data=np.array([10,20,np.nan,40,50])
new_data=np.where(np.isnan(data), 0.0,data)
print(new_data)

[10. 20.  0. 40. 50.]


In [11]:
#detect missing value
print(np.isnan(data))

[False False  True False False]


In [12]:
#removing nan values
data[~np.isnan(data)]

array([10., 20., 40., 50.])

In [15]:
#generate random numbers
ran=np.random.default_rng()
print(ran.random(5))

print(ran.integers(1,100, size=10))

[0.44380011 0.49586868 0.77541824 0.572536   0.10211063]
[36 30 65 26  3 92 90  5 48 45]


In [16]:
#2d random numbers
print(ran.integers(1,100, size=(5,3)))

[[85 60 40]
 [57 62 35]
 [ 4 36 16]
 [74 53  1]
 [27 16 24]]


In [17]:
#reproducible random numbers
ran=np.random.default_rng(42)
print(ran.integers(100,10000, size=10))


[ 983 7762 6580 4444 4386 8600  950 7003 2094 1032]


## student performance analaysis
```code
marks = np.array([
    [65, 70, 75],
    [80, 85, 90],
    [45, 55, 60],
    [90, 95, 92],
    [35, 40, 50],
    [72, 68, 75],
    [88, 82, 84],
    [55, 60, 58]
])
```
columns: Python | Mathematics | Statistics
 
### calculate
1. Average mark of every student
2. Average mark of every subject
3. Highest mark in the dataset
4. Lowest mark
5. Student with highest average
6. Students whose Python mark is above 70
7. Number of individual marks above 80
8. Students with an overall average below 50
9. Sort students based on overall average
10. Assign a result using:
```code
Average >= 80     → Distinction
Average >= 60     → First Division
Average >= 40     → Pass
Average < 40      → Fail
 

In [47]:
marks = np.array([
    [65, 70, 75],
    [80, 85, 90],
    [45, 55, 60],
    [90, 95, 92],
    [35, 40, 50],
    [72, 68, 75],
    [88, 82, 84],
    [55, 60, 58]
])

#Average marks of every student
average_marks=np.average(marks,axis=1)
print("The average marks of every students is:\n",average_marks)
#print("The average marks of each students is:\n",np.average(marks,axis=1))

#Average marks of every subject
print("The average marks of every subject is:\n",np.average(marks,axis=0))

#Highest marks
print("The highest marks in database is:",np.max(marks))

#Lowest mark
print("The lowest mark in database is:",np.min(marks))

#Student with highest average
print("The student with highest average is:",np.max(average_marks))

# python Marks above 70
print("The students marks of python above 70 are:\n",marks[marks[:,0]>70,0])

#Marks above 80
print("The individual whose marks are above 80 are\n:",marks[marks>80])

#Average below 50:
print("The individual whose marks are below 50 are\n:",average_marks[average_marks<50])

#sort based on average:
print("The sorted order based on the average marks is:\n",np.sort(average_marks))

#Assign a result:
#new_salary=np.where(salary<=4000, salary*1.2, salary*1.1)

result=np.select(
                [average_marks>=80,
                average_marks>=60,
                average_marks>=40],

                [
                    "Distinction",
                    "First division",
                    "Second division"
                ] ,
                default='fail'

                )
print(result)

The average marks of every students is:
 [70.         85.         53.33333333 92.33333333 41.66666667 71.66666667
 84.66666667 57.66666667]
The average marks of every subject is:
 [66.25  69.375 73.   ]
The highest marks in database is: 95
The lowest mark in database is: 35
The student with highest average is: 92.33333333333333
The students marks of python above 70 are:
 [80 90 72 88]
The individual whose marks are above 80 are
: [85 90 90 95 92 88 82 84]
The individual whose marks are below 50 are
: [41.66666667]
The sorted order based on the average marks is:
 [41.66666667 53.33333333 57.66666667 70.         71.66666667 84.66666667
 85.         92.33333333]
['First division' 'Distinction' 'Second division' 'Distinction'
 'Second division' 'First division' 'Distinction' 'Second division']


In [49]:
import pandas as pd
#custom index
ages=pd.series(
    [20,25,30,35],
    index=[1,2,3,4]
)

print(ages[2])

AttributeError: module 'pandas' has no attribute 'series'